### ISSUE TITLE
Convet error all the time

### ISSUE THREAD

**Issue by c2rx** [OpenVINO-dev-contest/chatglm3.openvino#17]
(openvino) [root@localhost openvino]# python3 convert.py --model_id /root/Glm4/GLM-4/glm-4-9b-chat/ --precision int8  --output /root/Glm4/Intel/glm-4-9b-chat-ov
====Exporting IR=====
Traceback (most recent call last):
  File "/root/Glm4/GLM-4/intel_device_demo/openvino/convert.py", line 61, in <module>
    ov_model = OVModelForCausalLM.from_pretrained(args.model_id, export=True,
  File "/root/anaconda3/envs/openvino/lib/python3.10/site-packages/optimum/modeling_base.py", line 424, in from_pretrained
    return from_pretrained_method(
  File "/root/anaconda3/envs/openvino/lib/python3.10/site-packages/optimum/intel/openvino/modeling_decoder.py", line 283, in _from_transformers
    main_export(
  File "/root/anaconda3/envs/openvino/lib/python3.10/site-packages/optimum/exporters/openvino/__main__.py", line 194, in main_export
    framework = TasksManager.determine_framework(model_name_or_path, subfolder=subfolder, framework=framework)
TypeError: TasksManager.determine_framework() got an unexpected keyword argument 'framework'

Keep popping same error as above, no matter using HF model or local downloaded model,please help me with it, thanks a lot!!

**Comment by openvino-dev-samples** [comment]
Hi @c2rx I cannot reproduce your issue.

Could you share the version of optimum and optimum-intel on your side ?

**Comment by c2rx** [comment]
optimum                   1.22.0                   pypi_0    pypi
optimum-intel             1.18.0.dev0+c1ee8ac          pypi_0    pypi

**Comment by c2rx** [comment]
(openvino) [root@localhost envs]# conda list
# packages in environment at /root/anaconda3/envs/openvino:
#
# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                 conda_forge    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
_openmp_mutex             4.5                       2_gnu    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
about-time                4.2.1                    pypi_0    pypi
aiohappyeyeballs          2.4.0                    pypi_0    pypi
aiohttp                   3.10.5                   pypi_0    pypi
aiosignal                 1.3.1                    pypi_0    pypi
alive-progress            3.1.5                    pypi_0    pypi
async-timeout             4.0.3                    pypi_0    pypi
attrs                     24.2.0                   pypi_0    pypi
autograd                  1.7.0                    pypi_0    pypi
bzip2                     1.0.8                h4bc722e_7    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
ca-certificates           2024.8.30            hbcca054_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
certifi                   2024.8.30                pypi_0    pypi
charset-normalizer        3.3.2                    pypi_0    pypi
cma                       3.2.2                    pypi_0    pypi
coloredlogs               15.0.1                   pypi_0    pypi
contourpy                 1.3.0                    pypi_0    pypi
cycler                    0.12.1                   pypi_0    pypi
datasets                  3.0.0                    pypi_0    pypi
deprecated                1.2.14                   pypi_0    pypi
dill                      0.3.8                    pypi_0    pypi
filelock                  3.16.0                   pypi_0    pypi
fonttools                 4.53.1                   pypi_0    pypi
frozenlist                1.4.1                    pypi_0    pypi
fsspec                    2024.6.1                 pypi_0    pypi
grapheme                  0.6.0                    pypi_0    pypi
huggingface-hub           0.24.7                   pypi_0    pypi
humanfriendly             10.0                     pypi_0    pypi
icu                       75.1                 he02047a_0    conda-forge
idna                      3.10                     pypi_0    pypi
jinja2                    3.1.4                    pypi_0    pypi
joblib                    1.4.2                    pypi_0    pypi
jsonschema                4.23.0                   pypi_0    pypi
jsonschema-specifications 2023.12.1                pypi_0    pypi
jstyleson                 0.0.2                    pypi_0    pypi
kiwisolver                1.4.7                    pypi_0    pypi
ld_impl_linux-64          2.40                 hf3520f5_7    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
libabseil                 20240116.2      cxx17_he02047a_1    conda-forge
libblas                   3.9.0           23_linux64_openblas    conda-forge
libcblas                  3.9.0           23_linux64_openblas    conda-forge
libffi                    3.4.2                h7f98852_5    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
libgcc                    14.1.0               h77fa898_1    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
libgcc-ng                 14.1.0               h69a702a_1    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
libgfortran               14.1.0               h69a702a_1    conda-forge
libgfortran-ng            14.1.0               h69a702a_1    conda-forge
libgfortran5              14.1.0               hc5f4f2c_1    conda-forge
libgomp                   14.1.0               h77fa898_1    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
libhwloc                  2.11.1          default_hecaa2ac_1000    conda-forge
libiconv                  1.17                 hd590300_2    conda-forge
liblapack                 3.9.0           23_linux64_openblas    conda-forge
libnsl                    2.0.1                hd590300_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
libopenblas               0.3.27          pthreads_hac2b453_1    conda-forge
libopenvino               2024.3.0             h2da1b83_0    conda-forge
libopenvino-auto-batch-plugin 2024.3.0             hb045406_0    conda-forge
libopenvino-auto-plugin   2024.3.0             hb045406_0    conda-forge
libopenvino-dev           2024.3.0             h64d3f89_0    conda-forge
libopenvino-hetero-plugin 2024.3.0             h5c03a75_0    conda-forge
libopenvino-intel-cpu-plugin 2024.3.0             h2da1b83_0    conda-forge
libopenvino-intel-gpu-plugin 2024.3.0             h2da1b83_0    conda-forge
libopenvino-intel-npu-plugin 2024.3.0             h2da1b83_0    conda-forge
libopenvino-ir-frontend   2024.3.0             h5c03a75_0    conda-forge
libopenvino-onnx-frontend 2024.3.0             h07e8aee_0    conda-forge
libopenvino-paddle-frontend 2024.3.0             h07e8aee_0    conda-forge
libopenvino-python        2024.3.0        py310h3ba7dcc_0    conda-forge
libopenvino-pytorch-frontend 2024.3.0             he02047a_0    conda-forge
libopenvino-tensorflow-frontend 2024.3.0             h39126c6_0    conda-forge
libopenvino-tensorflow-lite-frontend 2024.3.0             he02047a_0    conda-forge
libprotobuf               4.25.3               h08a7969_0    conda-forge
libsqlite                 3.46.1               hadc24fc_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
libstdcxx                 14.1.0               hc0a3c3a_1    conda-forge
libstdcxx-ng              14.1.0               h4852527_1    conda-forge
libuuid                   2.38.1               h0b41bf4_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
libxml2                   2.12.7               he7c6b58_4    conda-forge
libzlib                   1.3.1                h4ab18f5_1    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
markdown-it-py            3.0.0                    pypi_0    pypi
markupsafe                2.1.5                    pypi_0    pypi
matplotlib                3.9.2                    pypi_0    pypi
mdurl                     0.1.2                    pypi_0    pypi
mpmath                    1.3.0                    pypi_0    pypi
multidict                 6.1.0                    pypi_0    pypi
multiprocess              0.70.16                  pypi_0    pypi
natsort                   8.4.0                    pypi_0    pypi
ncurses                   6.5                  he02047a_1    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
networkx                  3.3                      pypi_0    pypi
ninja                     1.11.1.1                 pypi_0    pypi
nncf                      2.12.0                   pypi_0    pypi
numpy                     1.26.4          py310hb13e2d6_0    conda-forge
nvidia-cublas-cu12        12.1.3.1                 pypi_0    pypi
nvidia-cuda-cupti-cu12    12.1.105                 pypi_0    pypi
nvidia-cuda-nvrtc-cu12    12.1.105                 pypi_0    pypi
nvidia-cuda-runtime-cu12  12.1.105                 pypi_0    pypi
nvidia-cudnn-cu12         9.1.0.70                 pypi_0    pypi
nvidia-cufft-cu12         11.0.2.54                pypi_0    pypi
nvidia-curand-cu12        10.3.2.106               pypi_0    pypi
nvidia-cusolver-cu12      11.4.5.107               pypi_0    pypi
nvidia-cusparse-cu12      12.1.0.106               pypi_0    pypi
nvidia-nccl-cu12          2.20.5                   pypi_0    pypi
nvidia-nvjitlink-cu12     12.6.68                  pypi_0    pypi
nvidia-nvtx-cu12          12.1.105                 pypi_0    pypi
ocl-icd                   2.3.2                hd590300_1    conda-forge
onnx                      1.16.2                   pypi_0    pypi
openssl                   3.3.2                hb9d3cd8_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
openvino                  2024.3.0             h85509e4_0    conda-forge
openvino-telemetry        2024.1.0           pyhd8ed1ab_0    conda-forge
optimum                   1.22.0                   pypi_0    pypi
optimum-intel             1.18.0.dev0+c1ee8ac          pypi_0    pypi
packaging                 24.1               pyhd8ed1ab_0    conda-forge
pandas                    2.2.2                    pypi_0    pypi
pillow                    10.4.0                   pypi_0    pypi
pip                       24.2               pyh8b19718_1    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
protobuf                  5.28.1                   pypi_0    pypi
psutil                    6.0.0                    pypi_0    pypi
pugixml                   1.14                 h59595ed_0    conda-forge
pyarrow                   17.0.0                   pypi_0    pypi
pydot                     2.0.0                    pypi_0    pypi
pygments                  2.18.0                   pypi_0    pypi
pymoo                     0.6.1.3                  pypi_0    pypi
pyparsing                 3.1.4                    pypi_0    pypi
python                    3.10.0          h543edf9_3_cpython    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
python-dateutil           2.9.0.post0              pypi_0    pypi
python_abi                3.10                    5_cp310    conda-forge
pytz                      2024.2                   pypi_0    pypi
pyyaml                    6.0.2                    pypi_0    pypi
readline                  8.2                  h8228510_1    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
referencing               0.35.1                   pypi_0    pypi
regex                     2024.9.11                pypi_0    pypi
requests                  2.32.3                   pypi_0    pypi
rich                      13.8.1                   pypi_0    pypi
rpds-py                   0.20.0                   pypi_0    pypi
safetensors               0.4.5                    pypi_0    pypi
scikit-learn              1.5.2                    pypi_0    pypi
scipy                     1.14.1                   pypi_0    pypi
sentencepiece             0.2.0                    pypi_0    pypi
setuptools                73.0.1             pyhd8ed1ab_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
six                       1.16.0                   pypi_0    pypi
snappy                    1.2.1                ha2e4443_0    conda-forge
sqlite                    3.46.1               h9eae976_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
sympy                     1.13.2                   pypi_0    pypi
tabulate                  0.9.0                    pypi_0    pypi
tbb                       2021.13.0            h84d6215_0    conda-forge
tbb-devel                 2021.13.0            h94b29a5_0    conda-forge
threadpoolctl             3.5.0                    pypi_0    pypi
tk                        8.6.13          noxft_h4845f30_101    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
tokenizers                0.19.1                   pypi_0    pypi
torch                     2.4.1                    pypi_0    pypi
tqdm                      4.66.5                   pypi_0    pypi
transformers              4.41.2                   pypi_0    pypi
triton                    3.0.0                    pypi_0    pypi
typing-extensions         4.12.2                   pypi_0    pypi
tzdata                    2024.1                   pypi_0    pypi
urllib3                   2.2.3                    pypi_0    pypi
wheel                     0.44.0             pyhd8ed1ab_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
wrapt                     1.16.0                   pypi_0    pypi
xxhash                    3.5.0                    pypi_0    pypi
xz                        5.2.6                h166bdaf_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
yarl                      1.11.1                   pypi_0    pypi

Hi! Thanks for reply. Those are all the packages had been installed. I tended to run the GLM4 model under a CPU environment.

**Comment by openvino-dev-samples** [comment]
I think your `optimum-intel` is out of date, so you should uninstall it, and reinstall it without cache by ` pip install optimum-intel --no-cache-dir`

**Comment by dailinyucode** [comment]
I encountered the same problem as you， Have you solved it?

**Comment by dailinyucode** [comment]
I'd like to know what system architecture you have. it can help me solve this problem。

**Comment by c2rx** [comment]
Sorry, have not got it down yet. Just pass the itrex tool, could use a CPU based server to run GLM4. 

I used CentOS9 Stream and anaconda3.

> I'd like to know what system architecture you have. it can help me solve this problem。

**Comment by dailinyucode** [comment]
> Sorry, have not got it down yet. Just pass the itrex tool, could use a CPU based server to run GLM4.
> 
> I used CentOS9 Stream and anaconda3.
> 
> > I'd like to know what system architecture you have. it can help me solve this problem。

I solved it. Use the 1.19.0 version of optimal-intel to succeed.

**Comment by c2rx** [comment]
> > Sorry, have not got it down yet. Just pass the itrex tool, could use a CPU based server to run GLM4.
> > I used CentOS9 Stream and anaconda3.
> > > I'd like to know what system architecture you have. it can help me solve this problem。
> 
> I solved it. Use the 1.19.0 version of optimal-intel to succeed.

Congrats, I've ran it successfully under itrex last Friday, still working on it with openvino.
