### ISSUE TITLE
DLL load failed while importing nct_ufunc: Operation did not complete successfully because the file contains a virus or potentially unwanted software.

### ISSUE THREAD

**Issue by mattchai** [OpenVINO-dev-contest/chatglm3.openvino#4]
(chatglm3) C:\Intel\chatglm3.openvino>python chat.py --model_path c:/models/chatglm3-6b-ov-int4 --max_sequence_length 4096 --device CPU
INFO:nncf:NNCF initialized successfully. Supported frameworks detected: torch, onnx, openvino
Traceback (most recent call last):
  File "C:\env\chatglm3\lib\site-packages\transformers\utils\import_utils.py", line 1472, in _get_module
    return importlib.import_module("." + module_name, self.__name__)
  File "C:\Program Files\Python39\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 972, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "C:\env\chatglm3\lib\site-packages\transformers\data\__init__.py", line 26, in <module>
    from .metrics import glue_compute_metrics, xnli_compute_metrics
  File "C:\env\chatglm3\lib\site-packages\transformers\data\metrics\__init__.py", line 19, in <module>
    from scipy.stats import pearsonr, spearmanr
  File "C:\env\chatglm3\lib\site-packages\scipy\stats\__init__.py", line 606, in <module>
    from ._stats_py import *
  File "C:\env\chatglm3\lib\site-packages\scipy\stats\_stats_py.py", line 49, in <module>
    from . import distributions
  File "C:\env\chatglm3\lib\site-packages\scipy\stats\distributions.py", line 10, in <module>
    from . import _continuous_distns
  File "C:\env\chatglm3\lib\site-packages\scipy\stats\_continuous_distns.py", line 33, in <module>
    import scipy.stats._boost as _boost
  File "C:\env\chatglm3\lib\site-packages\scipy\stats\_boost\__init__.py", line 37, in <module>
    from scipy.stats._boost.nct_ufunc import (
ImportError: DLL load failed while importing nct_ufunc: Operation did not complete successfully because the file contains a virus or potentially unwanted software.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Intel\chatglm3.openvino\chat.py", line 4, in <module>
    from optimum.intel.openvino import OVModelForCausalLM
  File "C:\env\chatglm3\lib\site-packages\optimum\intel\openvino\__init__.py", line 39, in <module>
    from .quantization import OVQuantizer
  File "C:\env\chatglm3\lib\site-packages\optimum\intel\openvino\quantization.py", line 36, in <module>
    from transformers import AutoTokenizer, DataCollator, PreTrainedModel, default_data_collator
  File "<frozen importlib._bootstrap>", line 1055, in _handle_fromlist
  File "C:\env\chatglm3\lib\site-packages\transformers\utils\import_utils.py", line 1462, in __getattr__
    module = self._get_module(self._class_to_module[name])
  File "C:\env\chatglm3\lib\site-packages\transformers\utils\import_utils.py", line 1474, in _get_module
    raise RuntimeError(
RuntimeError: Failed to import transformers.data.data_collator because of the following error (look up to see its traceback):
DLL load failed while importing nct_ufunc: Operation did not complete successfully because the file contains a virus or potentially unwanted software.

**Comment by OpenVINO-dev-contest** [comment]
Please share the version of your transformers, optimum, and optimum-intel lib

**Comment by mattchai** [comment]
Hi, here is version, thanks.

transformers              4.39.3
openvino                  2024.0.0
openvino-telemetry        2023.2.1
optimum                   1.18.0
optimum-intel             1.16.0

**Comment by OpenVINO-dev-contest** [comment]
what‘s the version of Python, could you try running these script with Python 3.10 ?

**Comment by mattchai** [comment]
Hi, I can run chatglm3 after using python 3.10 on CPU and GPU.
**but got error message when try to run model on NPU, below is the error info:**

(chatglm_py10) C:\Intel\chatglm3.openvino>python chat.py --model_path c:/models/chatglm3-6b-ov-int4 --max_sequence_length 4096 --device NPU
INFO:nncf:NNCF initialized successfully. Supported frameworks detected: torch, onnx, openvino
Setting eos_token is not supported, use the default one.
Setting pad_token is not supported, use the default one.
Setting unk_token is not supported, use the default one.
====Compiling model====
The argument `trust_remote_code` is to be used along with export=True. It will be ignored.
Compiling the model to NPU ...
Traceback (most recent call last):
  File "C:\Intel\chatglm3.openvino\chat.py", line 87, in <module>
    ov_model = OVCHATGLMModel.from_pretrained(
  File "C:\env\chatglm_py10\lib\site-packages\optimum\modeling_base.py", line 401, in from_pretrained
    return from_pretrained_method(
  File "C:\env\chatglm_py10\lib\site-packages\optimum\intel\openvino\modeling_decoder.py", line 586, in _from_pretrained
    causal_model = init_cls(
  File "C:\env\chatglm_py10\lib\site-packages\optimum\intel\openvino\modeling_decoder.py", line 162, in __init__
    self.compile()
  File "C:\env\chatglm_py10\lib\site-packages\optimum\intel\openvino\modeling_decoder.py", line 324, in compile
    super().compile()
  File "C:\env\chatglm_py10\lib\site-packages\optimum\intel\openvino\modeling_base.py", line 400, in compile
    self.request = core.compile_model(self.model, self._device, ov_config)
  File "C:\env\chatglm_py10\lib\site-packages\openvino\runtime\ie_api.py", line 515, in compile_model
    super().compile_model(model, device_name, {} if config is None else config),
RuntimeError: Exception from src\inference\src\cpp\core.cpp:109:
Exception from src\inference\src\dev\plugin.cpp:54:
Exception from C:\Jenkins\workspace\private-ci\ie\build-windows-vs2019@2\b\repos\npu\src\vpux_plugin\src\plugin.cpp:461:
get_shape was called on a descriptor::Tensor with dynamic shape

(chatglm_py10) C:\Intel\chatglm3.openvino>

**Comment by OpenVINO-dev-contest** [comment]
hi @mattchai Since model with dynamic shape is not supported by NPU yet, you cannot run this example with NPU.

**Comment by mattchai** [comment]
Hi, could you please help to share any examples that can run with NPU, thanks a lot.

**Comment by OpenVINO-dev-contest** [comment]
@mattchai Sorry, I dont have this example currently, but if you can share your project information/Email, I can help to connect our customer support team for your request.
